(* generated by dune *)

(** @canonical Miaou_core.Capability *)
module Capability = Miaou_core__Capability

(** @canonical Miaou_core.File_browser_modal *)
module File_browser_modal = Miaou_core__File_browser_modal

(** @canonical Miaou_core.Help_hint *)
module Help_hint = Miaou_core__Help_hint

(** @canonical Miaou_core.Keys *)
module Keys = Miaou_core__Keys

(** @canonical Miaou_core.Lib_tui *)
module Lib_tui = Miaou_core__Lib_tui

(** @canonical Miaou_core.Logger *)
module Logger = Miaou_core__Logger

(** @canonical Miaou_core.Logger_alias *)
module Logger_alias = Miaou_core__Logger_alias

(** @canonical Miaou_core.Modal_manager *)
module Modal_manager = Miaou_core__Modal_manager

(** @canonical Miaou_core.Narrow_modal *)
module Narrow_modal = Miaou_core__Narrow_modal

(** @canonical Miaou_core.Navigation *)
module Navigation = Miaou_core__Navigation

(** @canonical Miaou_core.Quit_flag *)
module Quit_flag = Miaou_core__Quit_flag

(** @canonical Miaou_core.Registry *)
module Registry = Miaou_core__Registry

(** @canonical Miaou_core.Service_lifecycle *)
module Service_lifecycle = Miaou_core__Service_lifecycle

(** @canonical Miaou_core.System *)
module System = Miaou_core__System

(** @canonical Miaou_core.Tui_capture *)
module Tui_capture = Miaou_core__Tui_capture

(** @canonical Miaou_core.Tui_logger *)
module Tui_logger = Miaou_core__Tui_logger

(** @canonical Miaou_core.Tui_page *)
module Tui_page = Miaou_core__Tui_page

(** @canonical Miaou_core.Workflow *)
module Workflow = Miaou_core__Workflow
