(* generated by dune *)

(** @canonical Cohttp_eio.Body *)
module Body = Cohttp_eio__Body

(** @canonical Cohttp_eio.Client *)
module Client = Cohttp_eio__Client

(** @canonical Cohttp_eio.Io *)
module Io = Cohttp_eio__Io

(** @canonical Cohttp_eio.Server *)
module Server = Cohttp_eio__Server

(** @canonical Cohttp_eio.Utils *)
module Utils = Cohttp_eio__Utils

module Cohttp_eio__ = struct end
[@@deprecated "this module is shadowed"]
