(* generated by dune *)

(** @canonical Bisect_ppx.Exclude *)
module Exclude = Bisect_ppx__Exclude

(** @canonical Bisect_ppx.Exclude_lexer *)
module Exclude_lexer = Bisect_ppx__Exclude_lexer

(** @canonical Bisect_ppx.Exclude_parser *)
module Exclude_parser = Bisect_ppx__Exclude_parser

(** @canonical Bisect_ppx.Exclusions *)
module Exclusions = Bisect_ppx__Exclusions

(** @canonical Bisect_ppx.Instrument *)
module Instrument = Bisect_ppx__Instrument

(** @canonical Bisect_ppx.Register *)
module Register = Bisect_ppx__Register
