(* generated by dune *)

(** @canonical Ocamlformat_parser_standard.Ast_helper *)
module Ast_helper = Ocamlformat_parser_standard__Ast_helper

(** @canonical Ocamlformat_parser_standard.Ast_mapper *)
module Ast_mapper = Ocamlformat_parser_standard__Ast_mapper

(** @canonical Ocamlformat_parser_standard.Asttypes *)
module Asttypes = Ocamlformat_parser_standard__Asttypes

(** @canonical Ocamlformat_parser_standard.Docstrings *)
module Docstrings = Ocamlformat_parser_standard__Docstrings

(** @canonical Ocamlformat_parser_standard.Lexer *)
module Lexer = Ocamlformat_parser_standard__Lexer

(** @canonical Ocamlformat_parser_standard.Parse *)
module Parse = Ocamlformat_parser_standard__Parse

(** @canonical Ocamlformat_parser_standard.Parser *)
module Parser = Ocamlformat_parser_standard__Parser

(** @canonical Ocamlformat_parser_standard.Parsetree *)
module Parsetree = Ocamlformat_parser_standard__Parsetree

(** @canonical Ocamlformat_parser_standard.Pprintast *)
module Pprintast = Ocamlformat_parser_standard__Pprintast

(** @canonical Ocamlformat_parser_standard.Printast *)
module Printast = Ocamlformat_parser_standard__Printast
