(* generated by dune *)

(** @canonical Ocamlformat_parser_extended.Ast_helper *)
module Ast_helper = Ocamlformat_parser_extended__Ast_helper

(** @canonical Ocamlformat_parser_extended.Ast_mapper *)
module Ast_mapper = Ocamlformat_parser_extended__Ast_mapper

(** @canonical Ocamlformat_parser_extended.Asttypes *)
module Asttypes = Ocamlformat_parser_extended__Asttypes

(** @canonical Ocamlformat_parser_extended.Docstrings *)
module Docstrings = Ocamlformat_parser_extended__Docstrings

(** @canonical Ocamlformat_parser_extended.Lexer *)
module Lexer = Ocamlformat_parser_extended__Lexer

(** @canonical Ocamlformat_parser_extended.Parse *)
module Parse = Ocamlformat_parser_extended__Parse

(** @canonical Ocamlformat_parser_extended.Parser *)
module Parser = Ocamlformat_parser_extended__Parser

(** @canonical Ocamlformat_parser_extended.Parsetree *)
module Parsetree = Ocamlformat_parser_extended__Parsetree

(** @canonical Ocamlformat_parser_extended.Pprintast *)
module Pprintast = Ocamlformat_parser_extended__Pprintast

(** @canonical Ocamlformat_parser_extended.Printast *)
module Printast = Ocamlformat_parser_extended__Printast
