(* generated by dune *)

(** @canonical Miaou_widgets_navigation.Breadcrumbs_widget *)
module Breadcrumbs_widget = Miaou_widgets_navigation__Breadcrumbs_widget

(** @canonical Miaou_widgets_navigation.Link_widget *)
module Link_widget = Miaou_widgets_navigation__Link_widget

(** @canonical Miaou_widgets_navigation.Tabs_widget *)
module Tabs_widget = Miaou_widgets_navigation__Tabs_widget
