(* generated by dune *)

(** @canonical Miaou.Cohttp_net *)
module Cohttp_net = Miaou__Cohttp_net

(** @canonical Miaou.Net *)
module Net = Miaou__Net

module Miaou__ = struct end
[@@deprecated "this module is shadowed"]
