(* generated by dune *)

(** @canonical Ocamlformat_ocaml_common.Location *)
module Location = Ocamlformat_ocaml_common__Location

(** @canonical Ocamlformat_ocaml_common.Longident *)
module Longident = Ocamlformat_ocaml_common__Longident

(** @canonical Ocamlformat_ocaml_common.Syntaxerr *)
module Syntaxerr = Ocamlformat_ocaml_common__Syntaxerr

(** @canonical Ocamlformat_ocaml_common.Warnings *)
module Warnings = Ocamlformat_ocaml_common__Warnings
