(include_subdirs unqualified)

(data_only_dirs themes)

(library
 (name octez_manager_ui)
 (public_name octez-manager.ui)
 (libraries
  octez_manager_lib
  octez_manager_rewards
  miaou-core.lib
  miaou-core.interfaces
  miaou-core.internals
  miaou-core.widgets.display
  miaou-core.widgets.input
  miaou-core.widgets.layout
  miaou-core.widgets.navigation
  miaou-core.canvas
  miaou-core.style
  miaou-runner.tui
  lambda-term
  eio
  eio_main
  eio_posix
  eio.unix)
 (preprocess
  (pps ppx_deriving.show ppx_blob ppx_forbid))
 (preprocessor_deps
  (file themes/dark.json)
  (file themes/light.json))
 (instrumentation
  (backend bisect_ppx)))
