(* generated by dune *)

(** @canonical Miaou_widgets_display.Bar_chart_widget *)
module Bar_chart_widget = Miaou_widgets_display__Bar_chart_widget

(** @canonical Miaou_widgets_display.Braille_canvas *)
module Braille_canvas = Miaou_widgets_display__Braille_canvas

(** @canonical Miaou_widgets_display.Chart_utils *)
module Chart_utils = Miaou_widgets_display__Chart_utils

(** @canonical Miaou_widgets_display.Description_list *)
module Description_list = Miaou_widgets_display__Description_list

(** @canonical Miaou_widgets_display.File_pager *)
module File_pager = Miaou_widgets_display__File_pager

(** @canonical Miaou_widgets_display.Image_widget *)
module Image_widget = Miaou_widgets_display__Image_widget

(** @canonical Miaou_widgets_display.Line_chart_widget *)
module Line_chart_widget = Miaou_widgets_display__Line_chart_widget

(** @canonical Miaou_widgets_display.Pager_widget *)
module Pager_widget = Miaou_widgets_display__Pager_widget

(** @canonical Miaou_widgets_display.Palette *)
module Palette = Miaou_widgets_display__Palette

(** @canonical Miaou_widgets_display.Palette_sdl *)
module Palette_sdl = Miaou_widgets_display__Palette_sdl

(** @canonical Miaou_widgets_display.Qr_code_widget *)
module Qr_code_widget = Miaou_widgets_display__Qr_code_widget

(** @canonical Miaou_widgets_display.Sdl_chart_context *)
module Sdl_chart_context = Miaou_widgets_display__Sdl_chart_context

(** @canonical Miaou_widgets_display.Sparkline_widget *)
module Sparkline_widget = Miaou_widgets_display__Sparkline_widget

(** @canonical Miaou_widgets_display.Table_widget *)
module Table_widget = Miaou_widgets_display__Table_widget

(** @canonical Miaou_widgets_display.Table_widget_sdl *)
module Table_widget_sdl = Miaou_widgets_display__Table_widget_sdl

(** @canonical Miaou_widgets_display.Tree_widget *)
module Tree_widget = Miaou_widgets_display__Tree_widget

(** @canonical Miaou_widgets_display.Widgets *)
module Widgets = Miaou_widgets_display__Widgets
