(* generated by dune *)

(** @canonical Miaou_driver_matrix.Matrix_ansi_parser *)
module Matrix_ansi_parser = Miaou_driver_matrix__Matrix_ansi_parser

(** @canonical Miaou_driver_matrix.Matrix_ansi_writer *)
module Matrix_ansi_writer = Miaou_driver_matrix__Matrix_ansi_writer

(** @canonical Miaou_driver_matrix.Matrix_buffer *)
module Matrix_buffer = Miaou_driver_matrix__Matrix_buffer

(** @canonical Miaou_driver_matrix.Matrix_cell *)
module Matrix_cell = Miaou_driver_matrix__Matrix_cell

(** @canonical Miaou_driver_matrix.Matrix_config *)
module Matrix_config = Miaou_driver_matrix__Matrix_config

(** @canonical Miaou_driver_matrix.Matrix_diff *)
module Matrix_diff = Miaou_driver_matrix__Matrix_diff

(** @canonical Miaou_driver_matrix.Matrix_driver *)
module Matrix_driver = Miaou_driver_matrix__Matrix_driver

(** @canonical Miaou_driver_matrix.Matrix_input *)
module Matrix_input = Miaou_driver_matrix__Matrix_input

(** @canonical Miaou_driver_matrix.Matrix_render_loop *)
module Matrix_render_loop = Miaou_driver_matrix__Matrix_render_loop

(** @canonical Miaou_driver_matrix.Matrix_terminal *)
module Matrix_terminal = Miaou_driver_matrix__Matrix_terminal
