(* generated by dune *)

(** @canonical Miaou_widgets_layout.Card_widget *)
module Card_widget = Miaou_widgets_layout__Card_widget

(** @canonical Miaou_widgets_layout.File_browser_widget *)
module File_browser_widget = Miaou_widgets_layout__File_browser_widget

(** @canonical Miaou_widgets_layout.Flex_layout *)
module Flex_layout = Miaou_widgets_layout__Flex_layout

(** @canonical Miaou_widgets_layout.List_nav *)
module List_nav = Miaou_widgets_layout__List_nav

(** @canonical Miaou_widgets_layout.Pane *)
module Pane = Miaou_widgets_layout__Pane

(** @canonical Miaou_widgets_layout.Pane_layout *)
module Pane_layout = Miaou_widgets_layout__Pane_layout

(** @canonical Miaou_widgets_layout.Progress_widget *)
module Progress_widget = Miaou_widgets_layout__Progress_widget

(** @canonical Miaou_widgets_layout.Progress_widget_sdl *)
module Progress_widget_sdl = Miaou_widgets_layout__Progress_widget_sdl

(** @canonical Miaou_widgets_layout.Sidebar_widget *)
module Sidebar_widget = Miaou_widgets_layout__Sidebar_widget

(** @canonical Miaou_widgets_layout.Spinner_widget *)
module Spinner_widget = Miaou_widgets_layout__Spinner_widget

(** @canonical Miaou_widgets_layout.Spinner_widget_sdl *)
module Spinner_widget_sdl = Miaou_widgets_layout__Spinner_widget_sdl

(** @canonical Miaou_widgets_layout.Toast_widget *)
module Toast_widget = Miaou_widgets_layout__Toast_widget

(** @canonical Miaou_widgets_layout.Vsection *)
module Vsection = Miaou_widgets_layout__Vsection
