(* generated by dune *)

(** @canonical Miaou_widgets_input.Button_widget *)
module Button_widget = Miaou_widgets_input__Button_widget

(** @canonical Miaou_widgets_input.Checkbox_widget *)
module Checkbox_widget = Miaou_widgets_input__Checkbox_widget

(** @canonical Miaou_widgets_input.Event_result *)
module Event_result = Miaou_widgets_input__Event_result

(** @canonical Miaou_widgets_input.Radio_button_widget *)
module Radio_button_widget = Miaou_widgets_input__Radio_button_widget

(** @canonical Miaou_widgets_input.Select_widget *)
module Select_widget = Miaou_widgets_input__Select_widget

(** @canonical Miaou_widgets_input.Select_widget_sdl *)
module Select_widget_sdl = Miaou_widgets_input__Select_widget_sdl

(** @canonical Miaou_widgets_input.Switch_widget *)
module Switch_widget = Miaou_widgets_input__Switch_widget

(** @canonical Miaou_widgets_input.Textbox_widget *)
module Textbox_widget = Miaou_widgets_input__Textbox_widget

(** @canonical Miaou_widgets_input.Validated_textbox_widget *)
module Validated_textbox_widget = Miaou_widgets_input__Validated_textbox_widget
