(* generated by dune *)

(** @canonical Miaou_interfaces.Capability *)
module Capability = Miaou_interfaces__Capability

(** @canonical Miaou_interfaces.Logger_capability *)
module Logger_capability = Miaou_interfaces__Logger_capability

(** @canonical Miaou_interfaces.Palette *)
module Palette = Miaou_interfaces__Palette

(** @canonical Miaou_interfaces.Service_lifecycle *)
module Service_lifecycle = Miaou_interfaces__Service_lifecycle

(** @canonical Miaou_interfaces.System *)
module System = Miaou_interfaces__System
