(* generated by dune *)

(** @canonical Miaou_driver_term.Lambda_term_driver *)
module Lambda_term_driver = Miaou_driver_term__Lambda_term_driver

(** @canonical Miaou_driver_term.Term_event_reader *)
module Term_event_reader = Miaou_driver_term__Term_event_reader

(** @canonical Miaou_driver_term.Term_events *)
module Term_events = Miaou_driver_term__Term_events

(** @canonical Miaou_driver_term.Term_render *)
module Term_render = Miaou_driver_term__Term_render

(** @canonical Miaou_driver_term.Term_renderer *)
module Term_renderer = Miaou_driver_term__Term_renderer

(** @canonical Miaou_driver_term.Term_size_detection *)
module Term_size_detection = Miaou_driver_term__Term_size_detection

(** @canonical Miaou_driver_term.Term_terminal_setup *)
module Term_terminal_setup = Miaou_driver_term__Term_terminal_setup

(** @canonical Miaou_driver_term.Term_test_runner *)
module Term_test_runner = Miaou_driver_term__Term_test_runner
