(* generated by dune *)

(** @canonical Ocamlformat_parser_shims.Format_doc *)
module Format_doc = Ocamlformat_parser_shims__Format_doc

(** @canonical Ocamlformat_parser_shims.Misc_ *)
module Misc_ = Ocamlformat_parser_shims__Misc_
