(* generated by dune *)

(** @canonical Mew_vi.Core *)
module Core = Mew_vi__Core

(** @canonical Mew_vi.Edit_action *)
module Edit_action = Mew_vi__Edit_action

(** @canonical Mew_vi.Interpret *)
module Interpret = Mew_vi__Interpret

(** @canonical Mew_vi.Key *)
module Key = Mew_vi__Key

(** @canonical Mew_vi.Modal *)
module Modal = Mew_vi__Modal

(** @canonical Mew_vi.Mode *)
module Mode = Mew_vi__Mode

(** @canonical Mew_vi.Vi_action *)
module Vi_action = Mew_vi__Vi_action
