(* generated by dune *)

(** @canonical Miaou_driver_sdl.Sdl_ansi *)
module Sdl_ansi = Miaou_driver_sdl__Sdl_ansi

(** @canonical Miaou_driver_sdl.Sdl_colors *)
module Sdl_colors = Miaou_driver_sdl__Sdl_colors

(** @canonical Miaou_driver_sdl.Sdl_config *)
module Sdl_config = Miaou_driver_sdl__Sdl_config

(** @canonical Miaou_driver_sdl.Sdl_driver *)
module Sdl_driver = Miaou_driver_sdl__Sdl_driver

(** @canonical Miaou_driver_sdl.Sdl_enabled *)
module Sdl_enabled = Miaou_driver_sdl__Sdl_enabled

(** @canonical Miaou_driver_sdl.Sdl_events *)
module Sdl_events = Miaou_driver_sdl__Sdl_events

(** @canonical Miaou_driver_sdl.Sdl_font *)
module Sdl_font = Miaou_driver_sdl__Sdl_font

(** @canonical Miaou_driver_sdl.Sdl_render *)
module Sdl_render = Miaou_driver_sdl__Sdl_render

(** @canonical Miaou_driver_sdl.Sdl_renderer *)
module Sdl_renderer = Miaou_driver_sdl__Sdl_renderer

(** @canonical Miaou_driver_sdl.Sdl_text_render *)
module Sdl_text_render = Miaou_driver_sdl__Sdl_text_render

(** @canonical Miaou_driver_sdl.Sdl_transitions *)
module Sdl_transitions = Miaou_driver_sdl__Sdl_transitions

(** @canonical Miaou_driver_sdl.Sdl_window *)
module Sdl_window = Miaou_driver_sdl__Sdl_window
