(* generated by dune *)

(** @canonical Ocamlformat_odoc_parser.Ast *)
module Ast = Ocamlformat_odoc_parser__Ast

(** @canonical Ocamlformat_odoc_parser.Lexer *)
module Lexer = Ocamlformat_odoc_parser__Lexer

(** @canonical Ocamlformat_odoc_parser.Loc *)
module Loc = Ocamlformat_odoc_parser__Loc

(** @canonical Ocamlformat_odoc_parser.Odoc_parser *)
module Odoc_parser = Ocamlformat_odoc_parser__Odoc_parser

(** @canonical Ocamlformat_odoc_parser.Parse_error *)
module Parse_error = Ocamlformat_odoc_parser__Parse_error

(** @canonical Ocamlformat_odoc_parser.Syntax *)
module Syntax = Ocamlformat_odoc_parser__Syntax

(** @canonical Ocamlformat_odoc_parser.Token *)
module Token = Ocamlformat_odoc_parser__Token

(** @canonical Ocamlformat_odoc_parser.Warning *)
module Warning = Ocamlformat_odoc_parser__Warning
