# Bash completion for octez-manager
# Autogenerated by tools/gen_completion.ml. Do not edit.

_octez_manager_list_instances() {
  local cmd=""
  if [[ -x ./octez-manager ]]; then
    cmd=./octez-manager
  elif [[ -x _build/bin/octez-manager ]]; then
    cmd=_build/bin/octez-manager
  elif command -v octez-manager >/dev/null 2>&1; then
    cmd=octez-manager
  fi

  if [[ -n $cmd ]]; then
    local line
    while IFS= read -r line; do
      if [[ $line == *"("* ]]; then
        printf '%s\n' "${line%%[[:space:]]*}"
      fi
    done < <("$cmd" list 2>/dev/null)
  fi
}

_octez_manager() {
  local cur prev cmd action opts
  COMPREPLY=()
  cur="${COMP_WORDS[COMP_CWORD]}"
  prev="${COMP_WORDS[COMP_CWORD-1]}"

  local commands="binaries cleanup-dependencies cleanup-orphans import install-accuser install-baker install-dal-node install-node instance list list-available-networks list-snapshots purge-all self-update ui version"
  local instance_actions="start stop restart remove purge show show-service logs edit export-logs"
  local history_modes="archive full rolling"
  local snapshot_kinds="rolling full full:50 archive"
  local lb_votes="on off pass"

  if [[ $prev == --endpoint || $prev == --node-endpoint || $prev == --dal-endpoint ]]; then
    if declare -F _urls >/dev/null; then
      _urls
    else
      COMPREPLY=( $(compgen -W "http:// https://" -- "$cur") )
    fi
    return 0
  fi

  case "$prev" in
    --history-mode|--snapshot-history-mode)
      COMPREPLY=( $(compgen -W "$history_modes" -- "$cur") )
      return 0
      ;;
    --snapshot-kind)
      COMPREPLY=( $(compgen -W "$snapshot_kinds" -- "$cur") )
      return 0
      ;;
    --liquidity-baking-vote)
      COMPREPLY=( $(compgen -W "$lb_votes" -- "$cur") )
      return 0
      ;;
    --service-user)
      COMPREPLY=( $(compgen -A user -- "$cur") )
      return 0
      ;;
    --app-bin-dir|--data-dir|--base-dir|--node-data-dir)
      COMPREPLY=( $(compgen -d -- "$cur") )
      return 0
      ;;
    --log-file|--ui-logfile|--snapshot-uri)
      COMPREPLY=( $(compgen -f -- "$cur") )
      return 0
      ;;
    --tmp-dir)
      COMPREPLY=( $(compgen -d -- "$cur") )
      return 0
      ;;
  esac

  if [[ $COMP_CWORD -eq 1 ]]; then
    COMPREPLY=( $(compgen -W "$commands --help" -- "$cur") )
    return 0
  fi

  cmd="${COMP_WORDS[1]}"
  if [[ $cmd == -* ]]; then
    COMPREPLY=( $(compgen -W "$commands --help" -- "$cur") )
    return 0
  fi

  case "$cmd" in
    instance)
      if [[ $COMP_CWORD -eq 2 ]]; then
        local instances
        instances="$(_octez_manager_list_instances)"
        if [[ -n $instances ]]; then
          COMPREPLY=( $(compgen -W "$instances" -- "$cur") )
        fi
        return 0
      fi
      if [[ $COMP_CWORD -eq 3 ]]; then
        COMPREPLY=( $(compgen -W "$instance_actions --help" -- "$cur") )
        return 0
      fi
      if [[ $cur == -* ]]; then
        opts="--delete-data-dir --help --version"
        COMPREPLY=( $(compgen -W "$opts" -- "$cur") )
      fi
      return 0
      ;;
    binaries)
      if [[ $cur == -* ]]; then
        opts="--help --version"
        COMPREPLY=( $(compgen -W "$opts" -- "$cur") )
      fi
      return 0
      ;;
    cleanup-dependencies)
      if [[ $cur == -* ]]; then
        opts="--help --version"
        COMPREPLY=( $(compgen -W "$opts" -- "$cur") )
      fi
      return 0
      ;;
    cleanup-orphans)
      if [[ $cur == -* ]]; then
        opts="-n --dry-run --help --version"
        COMPREPLY=( $(compgen -W "$opts" -- "$cur") )
      fi
      return 0
      ;;
    import)
      if [[ $cur == -* ]]; then
        opts="-c --cascade -d --dry-run -i --interactive -n --network --name --as -s --strategy --help --version"
        COMPREPLY=( $(compgen -W "$opts" -- "$cur") )
      fi
      return 0
      ;;
    install-accuser)
      if [[ $cur == -* ]]; then
        opts="--app-bin-dir --base-dir --extra-arg --instance --no-enable --node-instance --service-user --help --version"
        COMPREPLY=( $(compgen -W "$opts" -- "$cur") )
      fi
      return 0
      ;;
    install-baker)
      if [[ $cur == -* ]]; then
        opts="--app-bin-dir --base-dir --dal-endpoint --delegate --extra-arg --instance --liquidity-baking-vote --no-enable --node-instance --service-user --help --version"
        COMPREPLY=( $(compgen -W "$opts" -- "$cur") )
      fi
      return 0
      ;;
    install-dal-node)
      if [[ $cur == -* ]]; then
        opts="--app-bin-dir --data-dir --extra-arg --instance --net-addr --no-enable --node-instance --rpc-addr --service-user --help --version"
        COMPREPLY=( $(compgen -W "$opts" -- "$cur") )
      fi
      return 0
      ;;
    install-node)
      if [[ $cur == -* ]]; then
        opts="--app-bin-dir --data-dir --extra-arg --history-mode --instance --keep-snapshot --net-addr --network --no-enable --preserve-data --rpc-addr --service-user --snapshot --snapshot-no-check --snapshot-uri --tmp-dir --help --version"
        COMPREPLY=( $(compgen -W "$opts" -- "$cur") )
      fi
      return 0
      ;;
    list)
      if [[ $cur == -* ]]; then
        opts="-a --all -e --external --help --version"
        COMPREPLY=( $(compgen -W "$opts" -- "$cur") )
      fi
      return 0
      ;;
    list-available-networks)
      if [[ $cur == -* ]]; then
        opts="--json --help --version"
        COMPREPLY=( $(compgen -W "$opts" -- "$cur") )
      fi
      return 0
      ;;
    list-snapshots)
      if [[ $cur == -* ]]; then
        opts="--json --network --help --version"
        COMPREPLY=( $(compgen -W "$opts" -- "$cur") )
      fi
      return 0
      ;;
    purge-all)
      if [[ $cur == -* ]]; then
        opts="--help --version"
        COMPREPLY=( $(compgen -W "$opts" -- "$cur") )
      fi
      return 0
      ;;
    self-update)
      if [[ $cur == -* ]]; then
        opts="-c --check -f --force --help --version"
        COMPREPLY=( $(compgen -W "$opts" -- "$cur") )
      fi
      return 0
      ;;
    ui)
      if [[ $cur == -* ]]; then
        opts="--page --ui-log --ui-logfile --help --version"
        COMPREPLY=( $(compgen -W "$opts" -- "$cur") )
      fi
      return 0
      ;;
    version)
      if [[ $cur == -* ]]; then
        opts="--help --version"
        COMPREPLY=( $(compgen -W "$opts" -- "$cur") )
      fi
      return 0
      ;;
  esac
}

complete -F _octez_manager octez-manager
