#compdef octez-manager

# Autogenerated by tools/gen_completion.ml. Do not edit.

_octez-manager() {
  local -a commands
  commands=(
    'cleanup-dependencies:Remove stale dependency entries from service configurations. This cleans up references to services that have been removed.'
    'cleanup-orphans:Remove orphan data directories and log files not associated with any registered service. Use --dry-run to preview what would be removed.'
    'install-accuser:Install an octez-accuser service'
    'install-baker:Install an octez-baker service'
    'install-dal-node:Install a DAL node service (octez-dal-node)'
    'install-node:Install an octez-node systemd instance'
    'instance:Manage existing Octez services.'
    'list:Show registered services'
    'list-available-networks:Show networks advertised on teztnets.com (with fallbacks).'
    'list-snapshots:List downloads published on snapshots.tzinit.org for a network.'
    'purge-all:Purge all registered instances. This removes each service, deletes data directories, log files, and (when run as root) drops service users that are no longer referenced by other services.'
    'ui:Launch the interactive terminal UI (same as running without arguments)'
  )

  local -a instance_actions
  instance_actions=(
    'start'
    'stop'
    'restart'
    'remove'
    'purge'
    'show'
    'show-service'
    'logs'
    'edit'
    'export-logs'
  )

  local -a history_modes
  history_modes=(
    'archive:Full archive mode'
    'full:Full mode'
    'rolling:Rolling mode'
  )

  local -a snapshot_kinds
  snapshot_kinds=(
    'rolling:Rolling snapshot'
    'full:Full snapshot'
    'full:50:Full snapshot with 50 cycles'
    'archive:Archive snapshot'
  )

  local -a lb_votes
  lb_votes=(
    'on:Vote for liquidity baking'
    'off:Vote against liquidity baking'
    'pass:Abstain from voting (default)'
  )

  local -a opts_cleanup_dependencies
  opts_cleanup_dependencies=(
    '--help[Show this help in format FMT. The value FMT must be one of auto, pager, groff or plain. With auto, the format is pager or plain whenever the TERM env var is dumb or undefined.]:FMT:'
    '--version[Show version information.]'
  )

  local -a opts_cleanup_orphans
  opts_cleanup_orphans=(
    '-n[Show what would be removed without actually deleting.]'
    '--dry-run[Show what would be removed without actually deleting.]'
    '--help[Show this help in format FMT. The value FMT must be one of auto, pager, groff or plain. With auto, the format is pager or plain whenever the TERM env var is dumb or undefined.]:FMT:'
    '--version[Show version information.]'
  )

  local -a opts_install_accuser
  opts_install_accuser=(
    '--app-bin-dir[Directory containing Octez binaries]:DIR:_directories'
    '--base-dir[Accuser base directory]:DIR:_directories'
    '--extra-arg[Additional arguments appended to the accuser command.]:ARG:'
    '--instance[Accuser instance name]:NAME:'
    '--no-enable[Disable automatic enable --now]'
    '--node-instance[Existing octez-manager node instance to reuse for endpoint; can also be a custom RPC endpoint]:NODE:'
    '--service-user[System user]:USER:_users'
    '--help[Show this help in format FMT. The value FMT must be one of auto, pager, groff or plain. With auto, the format is pager or plain whenever the TERM env var is dumb or undefined.]:FMT:'
    '--version[Show version information.]'
  )

  local -a opts_install_baker
  opts_install_baker=(
    '--app-bin-dir[Directory containing Octez binaries.]:DIR:_directories'
    '--base-dir[Baker base directory for wallets (defaults to an instance-specific path).]:DIR:_directories'
    '--dal-endpoint[DAL node endpoint (e.g., http://localhost:10732). Use '\''none'\'' to opt-out with --without-dal flag. Defaults to '\''none'\''.]:ENDPOINT:_urls'
    '--delegate[Delegate key hash or alias passed as --delegate.]:KEY:'
    '--extra-arg[Additional arguments appended to the baker command.]:ARG:'
    '--instance[Instance name for the baker systemd unit.]:NAME:'
    '--liquidity-baking-vote[Liquidity baking toggle vote (on, off or pass). Defaults to '\''pass'\''.]:VOTE:->lb-votes'
    '--no-enable[Disable automatic systemctl enable --now]'
    '--node-instance[Existing octez-manager node instance to reuse for data-dir and network. Use '\''octez-manager list'\'' to see available node instances. It can also be a custom RPC endpoint for the baker to contact. Defaults to http://127.0.0.1:8732]:NODE:'
    '--service-user[System user owning the service]:USER:_users'
    '--help[Show this help in format FMT. The value FMT must be one of auto, pager, groff or plain. With auto, the format is pager or plain whenever the TERM env var is dumb or undefined.]:FMT:'
    '--version[Show version information.]'
  )

  local -a opts_install_dal_node
  opts_install_dal_node=(
    '--app-bin-dir[Directory containing Octez binaries]:DIR:_directories'
    '--data-dir[DAL node data directory]:DIR:_directories'
    '--extra-arg[Additional arguments appended to the dal-node command.]:ARG:'
    '--instance[Instance name used for dal-node.env and systemd units.]:NAME:'
    '--net-addr[DAL node P2P address]:ADDR:'
    '--no-enable[Disable automatic enable --now]'
    '--node-instance[Existing octez-manager node instance to reuse for network resolution. It can also be a custom RPC endpoint for the DAL node to contact.]:NODE:'
    '--rpc-addr[DAL node RPC address]:ADDR:'
    '--service-user[System user]:USER:_users'
    '--help[Show this help in format FMT. The value FMT must be one of auto, pager, groff or plain. With auto, the format is pager or plain whenever the TERM env var is dumb or undefined.]:FMT:'
    '--version[Show version information.]'
  )

  local -a opts_install_node
  opts_install_node=(
    '--app-bin-dir[Directory containing Octez binaries (defaults to the directory holding octez-node found in $PATH).]:DIR:_directories'
    '--data-dir[Custom data directory (defaults to /var/lib/octez/<inst>).]:DIR:_directories'
    '--extra-arg[Additional arguments appended to the node command.]:ARG:'
    '--history-mode[History mode to configure on octez-node (rolling|full|archive).]:MODE:->history-modes'
    '--instance[Instance name used for node.env and systemd units.]:NAME:'
    '--keep-snapshot[Keep the downloaded snapshot file after import instead of deleting it.]'
    '--net-addr[P2P address]:ADDR:'
    '--network[Chain network (default: mainnet).]:NET:'
    '--no-enable[Disable automatic systemctl enable --now.]'
    '--preserve-data[Preserve existing data in data-dir instead of clearing it. When set, no snapshot will be imported even if --snapshot is specified.]'
    '--rpc-addr[RPC address]:ADDR:'
    '--service-user[System user owning the service.]:USER:_users'
    '--snapshot[Bootstrap by importing a snapshot before enabling the node service.]'
    '--snapshot-no-check[Pass --no-check to octez-node snapshot import during bootstrap.]'
    '--snapshot-uri[Snapshot URI (path, file://, or http(s)) to import when --snapshot is set.]:URI:'
    '--tmp-dir[Directory for temporary snapshot download. Use when /tmp has insufficient space for large snapshots (e.g., mainnet full).]:DIR:_directories'
    '--help[Show this help in format FMT. The value FMT must be one of auto, pager, groff or plain. With auto, the format is pager or plain whenever the TERM env var is dumb or undefined.]:FMT:'
    '--version[Show version information.]'
  )

  local -a opts_instance
  opts_instance=(
    '--delete-data-dir[Also delete the recorded data directory when removing.]'
    '--help[Show this help in format FMT. The value FMT must be one of auto, pager, groff or plain. With auto, the format is pager or plain whenever the TERM env var is dumb or undefined.]:FMT:'
    '--version[Show version information.]'
  )

  local -a opts_list
  opts_list=(
    '--help[Show this help in format FMT. The value FMT must be one of auto, pager, groff or plain. With auto, the format is pager or plain whenever the TERM env var is dumb or undefined.]:FMT:'
    '--version[Show version information.]'
  )

  local -a opts_list_available_networks
  opts_list_available_networks=(
    '--json[Emit JSON output instead of text.]'
    '--help[Show this help in format FMT. The value FMT must be one of auto, pager, groff or plain. With auto, the format is pager or plain whenever the TERM env var is dumb or undefined.]:FMT:'
    '--version[Show version information.]'
  )

  local -a opts_list_snapshots
  opts_list_snapshots=(
    '--json[Emit JSON output instead of text.]'
    '--network[Network alias or teztnets.json URL to inspect.]:NET:'
    '--help[Show this help in format FMT. The value FMT must be one of auto, pager, groff or plain. With auto, the format is pager or plain whenever the TERM env var is dumb or undefined.]:FMT:'
    '--version[Show version information.]'
  )

  local -a opts_purge_all
  opts_purge_all=(
    '--help[Show this help in format FMT. The value FMT must be one of auto, pager, groff or plain. With auto, the format is pager or plain whenever the TERM env var is dumb or undefined.]:FMT:'
    '--version[Show version information.]'
  )

  local -a opts_ui
  opts_ui=(
    '--page[Start on a registered page]:NAME:'
    '--ui-log[Enable UI debug logs]'
    '--ui-logfile[Write UI logs to FILE]:FILE:_files'
    '--help[Show this help in format FMT. The value FMT must be one of auto, pager, groff or plain. With auto, the format is pager or plain whenever the TERM env var is dumb or undefined.]:FMT:'
    '--version[Show version information.]'
  )

  _arguments -C \
    '1: :->command' \
    '*:: :->args'

  case $state in
    command)
      _describe -t commands 'octez-manager commands' commands
      ;;
    args)
      case $words[1] in
        instance)
          if (( CURRENT == 2 )); then
            local -a instances
            instances=()
            local cmd=""
            if [[ -x ./octez-manager ]]; then
              cmd=./octez-manager
            elif [[ -x _build/bin/octez-manager ]]; then
              cmd=_build/bin/octez-manager
            elif command -v octez-manager >/dev/null 2>&1; then
              cmd=octez-manager
            fi
            if [[ -n $cmd ]]; then
              local out
              out=$($cmd list 2>/dev/null)
              if [[ -n $out ]]; then
                while IFS= read -r line; do
                  if [[ $line == *'('* ]]; then
                    local inst=${line%%[[:space:]]*}
                    instances+=("$inst")
                  fi
                done <<<"$out"
              fi
            fi
            if (( ${#instances} )); then
              typeset -U instances
              _describe -t instances 'instances' instances
            else
              _message 'instance name'
            fi
          elif (( CURRENT == 3 )); then
            _describe -t actions 'instance actions' instance_actions
          else
            _arguments \
              $opts_instance
          fi
          ;;
        cleanup-dependencies)
          _arguments \
            $opts_cleanup_dependencies
          ;;
        cleanup-orphans)
          _arguments \
            $opts_cleanup_orphans
          ;;
        install-accuser)
          _arguments \
            $opts_install_accuser
          ;;
        install-baker)
          _arguments \
            $opts_install_baker
          ;;
        install-dal-node)
          _arguments \
            $opts_install_dal_node
          ;;
        install-node)
          _arguments \
            $opts_install_node
          ;;
        list)
          _arguments \
            $opts_list
          ;;
        list-available-networks)
          _arguments \
            $opts_list_available_networks
          ;;
        list-snapshots)
          _arguments \
            $opts_list_snapshots
          ;;
        purge-all)
          _arguments \
            $opts_purge_all
          ;;
        ui)
          _arguments \
            $opts_ui
          ;;
      esac
      ;;
  esac
}

if [[ -n $ZSH_VERSION ]]; then
  compdef _octez-manager octez-manager
fi
