# Bash completion for octez-manager
# Autogenerated by tools/gen_completion.ml. Do not edit.

_octez_manager_list_instances() {
  local cmd=""
  if [[ -x ./octez-manager ]]; then
    cmd=./octez-manager
  elif [[ -x _build/bin/octez-manager ]]; then
    cmd=_build/bin/octez-manager
  elif command -v octez-manager >/dev/null 2>&1; then
    cmd=octez-manager
  fi

  if [[ -n $cmd ]]; then
    local line
    while IFS= read -r line; do
      if [[ $line == *"("* ]]; then
        printf '%s\n' "${line%%[[:space:]]*}"
      fi
    done < <("$cmd" list 2>/dev/null)
  fi
}

_octez_manager() {
  local cur prev cmd action opts
  COMPREPLY=()
  cur="${COMP_WORDS[COMP_CWORD]}"
  prev="${COMP_WORDS[COMP_CWORD-1]}"

  local commands="baker binaries cleanup-dependencies cleanup-orphans group import install-accuser install-baker install-dal-node install-node install-signatory instance [ACTION] list list-available-networks list-snapshots purge-all rewards rpc sandbox self-update ui version web"
  local instance_actions="start stop restart remove purge show show-service logs edit export-logs set-env get-env"
  local history_modes="archive full rolling"
  local snapshot_kinds="rolling full full:50 archive"
  local lb_votes="on off pass"
  local _ACTION__baker_opts="--compare-indexers --indexer-network --local-indexer --page --theme --ui-log --ui-logfile --help --version"
  local _ACTION__binaries_opts="--compare-indexers --indexer-network --local-indexer --page --theme --ui-log --ui-logfile --help --version"
  local _ACTION__cleanup_dependencies_opts="--compare-indexers --indexer-network --local-indexer --page --theme --ui-log --ui-logfile --help --version"
  local _ACTION__cleanup_orphans_opts="--compare-indexers --indexer-network --local-indexer --page --theme --ui-log --ui-logfile --help --version"
  local _ACTION__group_opts="--compare-indexers --indexer-network --local-indexer --page --theme --ui-log --ui-logfile --help --version"
  local _ACTION__import_opts="--compare-indexers --indexer-network --local-indexer --page --theme --ui-log --ui-logfile --help --version"
  local _ACTION__install_accuser_opts="--compare-indexers --indexer-network --local-indexer --page --theme --ui-log --ui-logfile --help --version"
  local _ACTION__install_baker_opts="--compare-indexers --indexer-network --local-indexer --page --theme --ui-log --ui-logfile --help --version"
  local _ACTION__install_dal_node_opts="--compare-indexers --indexer-network --local-indexer --page --theme --ui-log --ui-logfile --help --version"
  local _ACTION__install_node_opts="--compare-indexers --indexer-network --local-indexer --page --theme --ui-log --ui-logfile --help --version"
  local _ACTION__install_signatory_opts="--compare-indexers --indexer-network --local-indexer --page --theme --ui-log --ui-logfile --help --version"
  local _ACTION__instance_opts="--compare-indexers --indexer-network --local-indexer --page --theme --ui-log --ui-logfile --help --version"
  local _ACTION__list_opts="--compare-indexers --indexer-network --local-indexer --page --theme --ui-log --ui-logfile --help --version"
  local _ACTION__list_available_networks_opts="--compare-indexers --indexer-network --local-indexer --page --theme --ui-log --ui-logfile --help --version"
  local _ACTION__list_snapshots_opts="--compare-indexers --indexer-network --local-indexer --page --theme --ui-log --ui-logfile --help --version"
  local _ACTION__purge_all_opts="--compare-indexers --indexer-network --local-indexer --page --theme --ui-log --ui-logfile --help --version"
  local _ACTION__rewards_opts="--compare-indexers --indexer-network --local-indexer --page --theme --ui-log --ui-logfile --help --version"
  local _ACTION__rpc_opts="--compare-indexers --indexer-network --local-indexer --page --theme --ui-log --ui-logfile --help --version"
  local _ACTION__sandbox_opts="--compare-indexers --indexer-network --local-indexer --page --theme --ui-log --ui-logfile --help --version"
  local _ACTION__self_update_opts="--compare-indexers --indexer-network --local-indexer --page --theme --ui-log --ui-logfile --help --version"
  local _ACTION__ui_opts="--compare-indexers --indexer-network --local-indexer --page --theme --ui-log --ui-logfile --help --version"
  local _ACTION__version_opts="--compare-indexers --indexer-network --local-indexer --page --theme --ui-log --ui-logfile --help --version"
  local _ACTION__web_opts="--compare-indexers --indexer-network --local-indexer --page --theme --ui-log --ui-logfile --help --version"
  local baker_finalize_unstake_opts="--delegate --json -y --yes --help --version"
  local baker_list_opts="--json --help --version"
  local baker_register_opts="--delegate --json -y --yes --help --version"
  local baker_set_delegate_params_opts="--delegate --edge-of-baking-over-staking --json --limit-of-staking-over-baking -y --yes --help --version"
  local baker_stake_opts="--delegate --json -y --yes --help --version"
  local baker_status_opts="--delegate --json --help --version"
  local baker_transfer_opts="--delegate --json -y --yes --help --version"
  local baker_unstake_opts="--delegate --json -y --yes --help --version"
  local baker_update_consensus_key_opts="--delegate --json -y --yes --help --version"
  local baker_vote_opts="--delegate --json -y --yes --help --version"
  local binaries_download_opts="--help --version"
  local binaries_list_opts="--help --version"
  local binaries_list_remote_opts="-a --all --help --version"
  local binaries_prune_opts="-n --dry-run --help --version"
  local binaries_register_opts="-a --alias --help --version"
  local binaries_remove_opts="--help --version"
  local binaries_unregister_opts="-f --force --help --version"
  local group_add_opts="--instance --help --version"
  local group_create_opts="--app-bin-dir --bin-dir-alias --network --octez-version --service-user --help --version"
  local group_delete_opts="--cascade --ungroup --help --version"
  local group_list_opts="--json --help --version"
  local group_remove_opts="--instance --help --version"
  local group_restart_opts="--help --version"
  local group_show_opts="--json --help --version"
  local group_start_opts="--help --version"
  local group_stop_opts="--help --version"
  local group_upgrade_opts="--app-bin-dir --bin-dir-alias --octez-version --help --version"
  local rewards_config_opts="--help --version"
  local rewards_continual_opts="--help --version"
  local rewards_generate_opts="--baker --cycle --force --json --help --version"
  local rewards_history_opts="--baker --cycles --json --help --version"
  local rewards_notify_opts="--help --version"
  local rewards_pay_opts="--baker --confirm --cycle --dry-run --help --version"
  local rewards_status_opts="--baker --help --version"
  local rpc_get_opts="-i --instance -p --public -u --url --help --version"
  local rpc_instances_opts="--help --version"
  local rpc_interactive_opts="-i --instance -p --public -u --url --help --version"
  local rpc_list_opts="-i --instance -p --public -u --url --help --version"
  local rpc_public_nodes_opts="--help --version"
  local sandbox_add_account_opts="--alias --help --version"
  local sandbox_create_opts="--accuser --app-bin-dir --bin-dir-alias --max-delegates -n --network --name --num-bakers --num-nodes --octez-version --rpc-addr --service-user --snapshot --help --version"
  local sandbox_destroy_opts="-y --yes --help --version"
  local sandbox_list_opts="--help --version"
  local sandbox_start_opts="--help --version"
  local sandbox_status_opts="--help --version"
  local sandbox_stop_opts="--help --version"

  if [[ $prev == --endpoint || $prev == --node-endpoint || $prev == --dal-endpoint ]]; then
    if declare -F _urls >/dev/null; then
      _urls
    else
      COMPREPLY=( $(compgen -W "http:// https://" -- "$cur") )
    fi
    return 0
  fi

  case "$prev" in
    --history-mode|--snapshot-history-mode)
      COMPREPLY=( $(compgen -W "$history_modes" -- "$cur") )
      return 0
      ;;
    --snapshot-kind)
      COMPREPLY=( $(compgen -W "$snapshot_kinds" -- "$cur") )
      return 0
      ;;
    --liquidity-baking-vote)
      COMPREPLY=( $(compgen -W "$lb_votes" -- "$cur") )
      return 0
      ;;
    --service-user)
      COMPREPLY=( $(compgen -A user -- "$cur") )
      return 0
      ;;
    --app-bin-dir|--data-dir|--base-dir|--node-data-dir)
      COMPREPLY=( $(compgen -d -- "$cur") )
      return 0
      ;;
    --log-file|--ui-logfile|--snapshot-uri)
      COMPREPLY=( $(compgen -f -- "$cur") )
      return 0
      ;;
    --bin-dir-alias|--signatory-version|--app-bin-dir.|--tmp-dir|--octez-version)
      COMPREPLY=( $(compgen -d -- "$cur") )
      return 0
      ;;
    --theme|--keys-dir|--watermark)
      COMPREPLY=( $(compgen -f -- "$cur") )
      return 0
      ;;
  esac

  if [[ $COMP_CWORD -eq 1 ]]; then
    COMPREPLY=( $(compgen -W "$commands --help" -- "$cur") )
    return 0
  fi

  cmd="${COMP_WORDS[1]}"
  if [[ $cmd == -* ]]; then
    COMPREPLY=( $(compgen -W "$commands --help" -- "$cur") )
    return 0
  fi

  case "$cmd" in
    instance)
      if [[ $COMP_CWORD -eq 2 ]]; then
        local instances
        instances="$(_octez_manager_list_instances)"
        if [[ -n $instances ]]; then
          COMPREPLY=( $(compgen -W "$instances" -- "$cur") )
        fi
        return 0
      fi
      if [[ $COMP_CWORD -eq 3 ]]; then
        COMPREPLY=( $(compgen -W "$instance_actions --help" -- "$cur") )
        return 0
      fi
      if [[ $cur == -* ]]; then
        opts="--delete-data-dir --force-purge --help --version"
        COMPREPLY=( $(compgen -W "$opts" -- "$cur") )
      fi
      return 0
      ;;
    [ACTION])
      if [[ $COMP_CWORD -eq 2 ]]; then
        if [[ $cur == -* ]]; then
          opts="--compare-indexers --indexer-network --local-indexer --page --theme --ui-log --ui-logfile --help --version"
          COMPREPLY=( $(compgen -W "$opts" -- "$cur") )
        else
          COMPREPLY=( $(compgen -W "baker binaries cleanup-dependencies cleanup-orphans group import install-accuser install-baker install-dal-node install-node install-signatory instance list list-available-networks list-snapshots purge-all rewards rpc sandbox self-update ui version web" -- "$cur") )
        fi
      else
        local subcmd="${COMP_WORDS[2]}"
        case "$subcmd" in
          baker)
            if [[ $cur == -* ]]; then
              COMPREPLY=( $(compgen -W "$_ACTION__baker_opts" -- "$cur") )
            fi
            ;;
          binaries)
            if [[ $cur == -* ]]; then
              COMPREPLY=( $(compgen -W "$_ACTION__binaries_opts" -- "$cur") )
            fi
            ;;
          cleanup-dependencies)
            if [[ $cur == -* ]]; then
              COMPREPLY=( $(compgen -W "$_ACTION__cleanup_dependencies_opts" -- "$cur") )
            fi
            ;;
          cleanup-orphans)
            if [[ $cur == -* ]]; then
              COMPREPLY=( $(compgen -W "$_ACTION__cleanup_orphans_opts" -- "$cur") )
            fi
            ;;
          group)
            if [[ $cur == -* ]]; then
              COMPREPLY=( $(compgen -W "$_ACTION__group_opts" -- "$cur") )
            fi
            ;;
          import)
            if [[ $cur == -* ]]; then
              COMPREPLY=( $(compgen -W "$_ACTION__import_opts" -- "$cur") )
            fi
            ;;
          install-accuser)
            if [[ $cur == -* ]]; then
              COMPREPLY=( $(compgen -W "$_ACTION__install_accuser_opts" -- "$cur") )
            fi
            ;;
          install-baker)
            if [[ $cur == -* ]]; then
              COMPREPLY=( $(compgen -W "$_ACTION__install_baker_opts" -- "$cur") )
            fi
            ;;
          install-dal-node)
            if [[ $cur == -* ]]; then
              COMPREPLY=( $(compgen -W "$_ACTION__install_dal_node_opts" -- "$cur") )
            fi
            ;;
          install-node)
            if [[ $cur == -* ]]; then
              COMPREPLY=( $(compgen -W "$_ACTION__install_node_opts" -- "$cur") )
            fi
            ;;
          install-signatory)
            if [[ $cur == -* ]]; then
              COMPREPLY=( $(compgen -W "$_ACTION__install_signatory_opts" -- "$cur") )
            fi
            ;;
          instance)
            if [[ $cur == -* ]]; then
              COMPREPLY=( $(compgen -W "$_ACTION__instance_opts" -- "$cur") )
            fi
            ;;
          list)
            if [[ $cur == -* ]]; then
              COMPREPLY=( $(compgen -W "$_ACTION__list_opts" -- "$cur") )
            fi
            ;;
          list-available-networks)
            if [[ $cur == -* ]]; then
              COMPREPLY=( $(compgen -W "$_ACTION__list_available_networks_opts" -- "$cur") )
            fi
            ;;
          list-snapshots)
            if [[ $cur == -* ]]; then
              COMPREPLY=( $(compgen -W "$_ACTION__list_snapshots_opts" -- "$cur") )
            fi
            ;;
          purge-all)
            if [[ $cur == -* ]]; then
              COMPREPLY=( $(compgen -W "$_ACTION__purge_all_opts" -- "$cur") )
            fi
            ;;
          rewards)
            if [[ $cur == -* ]]; then
              COMPREPLY=( $(compgen -W "$_ACTION__rewards_opts" -- "$cur") )
            fi
            ;;
          rpc)
            if [[ $cur == -* ]]; then
              COMPREPLY=( $(compgen -W "$_ACTION__rpc_opts" -- "$cur") )
            fi
            ;;
          sandbox)
            if [[ $cur == -* ]]; then
              COMPREPLY=( $(compgen -W "$_ACTION__sandbox_opts" -- "$cur") )
            fi
            ;;
          self-update)
            if [[ $cur == -* ]]; then
              COMPREPLY=( $(compgen -W "$_ACTION__self_update_opts" -- "$cur") )
            fi
            ;;
          ui)
            if [[ $cur == -* ]]; then
              COMPREPLY=( $(compgen -W "$_ACTION__ui_opts" -- "$cur") )
            fi
            ;;
          version)
            if [[ $cur == -* ]]; then
              COMPREPLY=( $(compgen -W "$_ACTION__version_opts" -- "$cur") )
            fi
            ;;
          web)
            if [[ $cur == -* ]]; then
              COMPREPLY=( $(compgen -W "$_ACTION__web_opts" -- "$cur") )
            fi
            ;;
        esac
      fi
      return 0
      ;;
    baker)
      if [[ $COMP_CWORD -eq 2 ]]; then
        if [[ $cur == -* ]]; then
          opts="--help --version"
          COMPREPLY=( $(compgen -W "$opts" -- "$cur") )
        else
          COMPREPLY=( $(compgen -W "finalize-unstake list register set-delegate-params stake status transfer unstake update-consensus-key vote" -- "$cur") )
        fi
      else
        local subcmd="${COMP_WORDS[2]}"
        case "$subcmd" in
          finalize-unstake)
            if [[ $cur == -* ]]; then
              COMPREPLY=( $(compgen -W "$baker_finalize_unstake_opts" -- "$cur") )
            fi
            ;;
          list)
            if [[ $cur == -* ]]; then
              COMPREPLY=( $(compgen -W "$baker_list_opts" -- "$cur") )
            fi
            ;;
          register)
            if [[ $cur == -* ]]; then
              COMPREPLY=( $(compgen -W "$baker_register_opts" -- "$cur") )
            fi
            ;;
          set-delegate-params)
            if [[ $cur == -* ]]; then
              COMPREPLY=( $(compgen -W "$baker_set_delegate_params_opts" -- "$cur") )
            fi
            ;;
          stake)
            if [[ $cur == -* ]]; then
              COMPREPLY=( $(compgen -W "$baker_stake_opts" -- "$cur") )
            fi
            ;;
          status)
            if [[ $cur == -* ]]; then
              COMPREPLY=( $(compgen -W "$baker_status_opts" -- "$cur") )
            fi
            ;;
          transfer)
            if [[ $cur == -* ]]; then
              COMPREPLY=( $(compgen -W "$baker_transfer_opts" -- "$cur") )
            fi
            ;;
          unstake)
            if [[ $cur == -* ]]; then
              COMPREPLY=( $(compgen -W "$baker_unstake_opts" -- "$cur") )
            fi
            ;;
          update-consensus-key)
            if [[ $cur == -* ]]; then
              COMPREPLY=( $(compgen -W "$baker_update_consensus_key_opts" -- "$cur") )
            fi
            ;;
          vote)
            if [[ $cur == -* ]]; then
              COMPREPLY=( $(compgen -W "$baker_vote_opts" -- "$cur") )
            fi
            ;;
        esac
      fi
      return 0
      ;;
    binaries)
      if [[ $COMP_CWORD -eq 2 ]]; then
        if [[ $cur == -* ]]; then
          opts="--help --version"
          COMPREPLY=( $(compgen -W "$opts" -- "$cur") )
        else
          COMPREPLY=( $(compgen -W "download list list-remote prune register remove unregister" -- "$cur") )
        fi
      else
        local subcmd="${COMP_WORDS[2]}"
        case "$subcmd" in
          download)
            if [[ $cur == -* ]]; then
              COMPREPLY=( $(compgen -W "$binaries_download_opts" -- "$cur") )
            fi
            ;;
          list)
            if [[ $cur == -* ]]; then
              COMPREPLY=( $(compgen -W "$binaries_list_opts" -- "$cur") )
            fi
            ;;
          list-remote)
            if [[ $cur == -* ]]; then
              COMPREPLY=( $(compgen -W "$binaries_list_remote_opts" -- "$cur") )
            fi
            ;;
          prune)
            if [[ $cur == -* ]]; then
              COMPREPLY=( $(compgen -W "$binaries_prune_opts" -- "$cur") )
            fi
            ;;
          register)
            if [[ $cur == -* ]]; then
              COMPREPLY=( $(compgen -W "$binaries_register_opts" -- "$cur") )
            fi
            ;;
          remove)
            if [[ $cur == -* ]]; then
              COMPREPLY=( $(compgen -W "$binaries_remove_opts" -- "$cur") )
            fi
            ;;
          unregister)
            if [[ $cur == -* ]]; then
              COMPREPLY=( $(compgen -W "$binaries_unregister_opts" -- "$cur") )
            fi
            ;;
        esac
      fi
      return 0
      ;;
    cleanup-dependencies)
      if [[ $cur == -* ]]; then
        opts="--help --version"
        COMPREPLY=( $(compgen -W "$opts" -- "$cur") )
      fi
      return 0
      ;;
    cleanup-orphans)
      if [[ $cur == -* ]]; then
        opts="-n --dry-run --help --version"
        COMPREPLY=( $(compgen -W "$opts" -- "$cur") )
      fi
      return 0
      ;;
    group)
      if [[ $COMP_CWORD -eq 2 ]]; then
        if [[ $cur == -* ]]; then
          opts="--help --version"
          COMPREPLY=( $(compgen -W "$opts" -- "$cur") )
        else
          COMPREPLY=( $(compgen -W "add create delete list remove restart show start stop upgrade" -- "$cur") )
        fi
      else
        local subcmd="${COMP_WORDS[2]}"
        case "$subcmd" in
          add)
            if [[ $cur == -* ]]; then
              COMPREPLY=( $(compgen -W "$group_add_opts" -- "$cur") )
            fi
            ;;
          create)
            if [[ $cur == -* ]]; then
              COMPREPLY=( $(compgen -W "$group_create_opts" -- "$cur") )
            fi
            ;;
          delete)
            if [[ $cur == -* ]]; then
              COMPREPLY=( $(compgen -W "$group_delete_opts" -- "$cur") )
            fi
            ;;
          list)
            if [[ $cur == -* ]]; then
              COMPREPLY=( $(compgen -W "$group_list_opts" -- "$cur") )
            fi
            ;;
          remove)
            if [[ $cur == -* ]]; then
              COMPREPLY=( $(compgen -W "$group_remove_opts" -- "$cur") )
            fi
            ;;
          restart)
            if [[ $cur == -* ]]; then
              COMPREPLY=( $(compgen -W "$group_restart_opts" -- "$cur") )
            fi
            ;;
          show)
            if [[ $cur == -* ]]; then
              COMPREPLY=( $(compgen -W "$group_show_opts" -- "$cur") )
            fi
            ;;
          start)
            if [[ $cur == -* ]]; then
              COMPREPLY=( $(compgen -W "$group_start_opts" -- "$cur") )
            fi
            ;;
          stop)
            if [[ $cur == -* ]]; then
              COMPREPLY=( $(compgen -W "$group_stop_opts" -- "$cur") )
            fi
            ;;
          upgrade)
            if [[ $cur == -* ]]; then
              COMPREPLY=( $(compgen -W "$group_upgrade_opts" -- "$cur") )
            fi
            ;;
        esac
      fi
      return 0
      ;;
    import)
      if [[ $cur == -* ]]; then
        opts="-c --cascade -d --dry-run -i --interactive -n --network --name --as -s --strategy --help --version"
        COMPREPLY=( $(compgen -W "$opts" -- "$cur") )
      fi
      return 0
      ;;
    install-accuser)
      if [[ $cur == -* ]]; then
        opts="--app-bin-dir --base-dir --bin-dir-alias --extra-arg --instance --no-enable --node-instance --octez-version --app-bin-dir. --service-user --help --version"
        COMPREPLY=( $(compgen -W "$opts" -- "$cur") )
      fi
      return 0
      ;;
    install-baker)
      if [[ $cur == -* ]]; then
        opts="--app-bin-dir --base-dir --bin-dir-alias --dal-endpoint --delegate --extra-arg --instance --liquidity-baking-vote --no-enable --node-instance --octez-version --app-bin-dir. --remote-signer-instance --remote-signer-uri --service-user --help --version"
        COMPREPLY=( $(compgen -W "$opts" -- "$cur") )
      fi
      return 0
      ;;
    install-dal-node)
      if [[ $cur == -* ]]; then
        opts="--app-bin-dir --bin-dir-alias --data-dir --extra-arg --instance --net-addr --no-enable --node-instance --octez-version --rpc-addr --service-user --help --version"
        COMPREPLY=( $(compgen -W "$opts" -- "$cur") )
      fi
      return 0
      ;;
    install-node)
      if [[ $cur == -* ]]; then
        opts="--app-bin-dir --bin-dir-alias --data-dir --extra-arg --history-mode --instance --keep-snapshot --net-addr --network --no-enable --octez-version --app-bin-dir. --preserve-data --rpc-addr --service-user --snapshot --snapshot-no-check --snapshot-uri --tmp-dir --help --version"
        COMPREPLY=( $(compgen -W "$opts" -- "$cur") )
      fi
      return 0
      ;;
    install-signatory)
      if [[ $cur == -* ]]; then
        opts="--address --app-bin-dir --authorized-keys --backend --bin-dir-alias --instance --keys-dir --metrics-address --no-enable --service-user --signatory-version --watermark --help --version"
        COMPREPLY=( $(compgen -W "$opts" -- "$cur") )
      fi
      return 0
      ;;
    list)
      if [[ $cur == -* ]]; then
        opts="-a --all -e --external -i --internal --help --version"
        COMPREPLY=( $(compgen -W "$opts" -- "$cur") )
      fi
      return 0
      ;;
    list-available-networks)
      if [[ $cur == -* ]]; then
        opts="--json --help --version"
        COMPREPLY=( $(compgen -W "$opts" -- "$cur") )
      fi
      return 0
      ;;
    list-snapshots)
      if [[ $cur == -* ]]; then
        opts="--json --network --help --version"
        COMPREPLY=( $(compgen -W "$opts" -- "$cur") )
      fi
      return 0
      ;;
    purge-all)
      if [[ $cur == -* ]]; then
        opts="--force-purge --help --version"
        COMPREPLY=( $(compgen -W "$opts" -- "$cur") )
      fi
      return 0
      ;;
    rewards)
      if [[ $COMP_CWORD -eq 2 ]]; then
        if [[ $cur == -* ]]; then
          opts="--help --version"
          COMPREPLY=( $(compgen -W "$opts" -- "$cur") )
        else
          COMPREPLY=( $(compgen -W "config continual generate history notify pay status" -- "$cur") )
        fi
      else
        local subcmd="${COMP_WORDS[2]}"
        case "$subcmd" in
          config)
            if [[ $cur == -* ]]; then
              COMPREPLY=( $(compgen -W "$rewards_config_opts" -- "$cur") )
            fi
            ;;
          continual)
            if [[ $cur == -* ]]; then
              COMPREPLY=( $(compgen -W "$rewards_continual_opts" -- "$cur") )
            fi
            ;;
          generate)
            if [[ $cur == -* ]]; then
              COMPREPLY=( $(compgen -W "$rewards_generate_opts" -- "$cur") )
            fi
            ;;
          history)
            if [[ $cur == -* ]]; then
              COMPREPLY=( $(compgen -W "$rewards_history_opts" -- "$cur") )
            fi
            ;;
          notify)
            if [[ $cur == -* ]]; then
              COMPREPLY=( $(compgen -W "$rewards_notify_opts" -- "$cur") )
            fi
            ;;
          pay)
            if [[ $cur == -* ]]; then
              COMPREPLY=( $(compgen -W "$rewards_pay_opts" -- "$cur") )
            fi
            ;;
          status)
            if [[ $cur == -* ]]; then
              COMPREPLY=( $(compgen -W "$rewards_status_opts" -- "$cur") )
            fi
            ;;
        esac
      fi
      return 0
      ;;
    rpc)
      if [[ $COMP_CWORD -eq 2 ]]; then
        if [[ $cur == -* ]]; then
          opts="--help --version"
          COMPREPLY=( $(compgen -W "$opts" -- "$cur") )
        else
          COMPREPLY=( $(compgen -W "get instances interactive list public-nodes" -- "$cur") )
        fi
      else
        local subcmd="${COMP_WORDS[2]}"
        case "$subcmd" in
          get)
            if [[ $cur == -* ]]; then
              COMPREPLY=( $(compgen -W "$rpc_get_opts" -- "$cur") )
            fi
            ;;
          instances)
            if [[ $cur == -* ]]; then
              COMPREPLY=( $(compgen -W "$rpc_instances_opts" -- "$cur") )
            fi
            ;;
          interactive)
            if [[ $cur == -* ]]; then
              COMPREPLY=( $(compgen -W "$rpc_interactive_opts" -- "$cur") )
            fi
            ;;
          list)
            if [[ $cur == -* ]]; then
              COMPREPLY=( $(compgen -W "$rpc_list_opts" -- "$cur") )
            fi
            ;;
          public-nodes)
            if [[ $cur == -* ]]; then
              COMPREPLY=( $(compgen -W "$rpc_public_nodes_opts" -- "$cur") )
            fi
            ;;
        esac
      fi
      return 0
      ;;
    sandbox)
      if [[ $COMP_CWORD -eq 2 ]]; then
        if [[ $cur == -* ]]; then
          opts="--help --version"
          COMPREPLY=( $(compgen -W "$opts" -- "$cur") )
        else
          COMPREPLY=( $(compgen -W "add-account create destroy list start status stop" -- "$cur") )
        fi
      else
        local subcmd="${COMP_WORDS[2]}"
        case "$subcmd" in
          add-account)
            if [[ $cur == -* ]]; then
              COMPREPLY=( $(compgen -W "$sandbox_add_account_opts" -- "$cur") )
            fi
            ;;
          create)
            if [[ $cur == -* ]]; then
              COMPREPLY=( $(compgen -W "$sandbox_create_opts" -- "$cur") )
            fi
            ;;
          destroy)
            if [[ $cur == -* ]]; then
              COMPREPLY=( $(compgen -W "$sandbox_destroy_opts" -- "$cur") )
            fi
            ;;
          list)
            if [[ $cur == -* ]]; then
              COMPREPLY=( $(compgen -W "$sandbox_list_opts" -- "$cur") )
            fi
            ;;
          start)
            if [[ $cur == -* ]]; then
              COMPREPLY=( $(compgen -W "$sandbox_start_opts" -- "$cur") )
            fi
            ;;
          status)
            if [[ $cur == -* ]]; then
              COMPREPLY=( $(compgen -W "$sandbox_status_opts" -- "$cur") )
            fi
            ;;
          stop)
            if [[ $cur == -* ]]; then
              COMPREPLY=( $(compgen -W "$sandbox_stop_opts" -- "$cur") )
            fi
            ;;
        esac
      fi
      return 0
      ;;
    self-update)
      if [[ $cur == -* ]]; then
        opts="-c --check -f --force --help --version"
        COMPREPLY=( $(compgen -W "$opts" -- "$cur") )
      fi
      return 0
      ;;
    ui)
      if [[ $cur == -* ]]; then
        opts="--compare-indexers --indexer-network --local-indexer --page --theme --ui-log --ui-logfile --help --version"
        COMPREPLY=( $(compgen -W "$opts" -- "$cur") )
      fi
      return 0
      ;;
    version)
      if [[ $cur == -* ]]; then
        opts="--help --version"
        COMPREPLY=( $(compgen -W "$opts" -- "$cur") )
      fi
      return 0
      ;;
    web)
      if [[ $cur == -* ]]; then
        opts="-p --port --page --password --theme --ui-log --ui-logfile --viewer-password --help --version"
        COMPREPLY=( $(compgen -W "$opts" -- "$cur") )
      fi
      return 0
      ;;
  esac
}

complete -F _octez_manager octez-manager
