(* generated by dune *)

(** @canonical Ocamlformat_stdlib.Fpath_ext *)
module Fpath_ext = Ocamlformat_stdlib__Fpath_ext

(** @canonical Ocamlformat_stdlib.List_ext *)
module List_ext = Ocamlformat_stdlib__List_ext

(** @canonical Ocamlformat_stdlib.String_ext *)
module String_ext = Ocamlformat_stdlib__String_ext

(** @canonical Ocamlformat_stdlib.Warning *)
module Warning = Ocamlformat_stdlib__Warning
