(* generated by dune *)

(** @canonical Miaou_widgets_display_sdl.Image_widget_sdl *)
module Image_widget_sdl = Miaou_widgets_display_sdl__Image_widget_sdl

(** @canonical Miaou_widgets_display_sdl.Line_chart_widget_sdl *)
module Line_chart_widget_sdl = Miaou_widgets_display_sdl__Line_chart_widget_sdl

(** @canonical Miaou_widgets_display_sdl.Qr_code_widget_sdl *)
module Qr_code_widget_sdl = Miaou_widgets_display_sdl__Qr_code_widget_sdl

(** @canonical Miaou_widgets_display_sdl.Sparkline_widget_sdl *)
module Sparkline_widget_sdl = Miaou_widgets_display_sdl__Sparkline_widget_sdl
