(* generated by dune *)

(** @canonical Ocamlformat_rpc_lib_protocol.IO *)
module IO = Ocamlformat_rpc_lib_protocol__IO

(** @canonical Ocamlformat_rpc_lib_protocol.Protocol *)
module Protocol = Ocamlformat_rpc_lib_protocol__Protocol
