(library
 (name gen_completion_helpers)
 (wrapped false)
 (modules gen_completion_helpers))

(executable
 (name gen_completion)
 (public_name octez-manager-gen-completion)
 (modules gen_completion)
 (libraries gen_completion_helpers octez_manager_lib rresult))

(executable
 (name arch_index)
 (modules arch_index)
 (libraries compiler-libs.common sqlite3 unix))

(executable
 (name arch_query)
 (modules arch_query)
 (libraries sqlite3 cmdliner str))
