(* generated by dune *)

(** @canonical Miaou_driver_common.Driver_common *)
module Driver_common = Miaou_driver_common__Driver_common

(** @canonical Miaou_driver_common.Input_parser *)
module Input_parser = Miaou_driver_common__Input_parser

(** @canonical Miaou_driver_common.Page_transition_utils *)
module Page_transition_utils = Miaou_driver_common__Page_transition_utils

(** @canonical Miaou_driver_common.Pager_notify *)
module Pager_notify = Miaou_driver_common__Pager_notify

(** @canonical Miaou_driver_common.Terminal_raw *)
module Terminal_raw = Miaou_driver_common__Terminal_raw
