(* generated by dune *)

(** @canonical Miaou_runner_common.Html_driver *)
module Html_driver = Miaou_runner_common__Html_driver

(** @canonical Miaou_runner_common.Runner_cli *)
module Runner_cli = Miaou_runner_common__Runner_cli

(** @canonical Miaou_runner_common.Tui_driver_common *)
module Tui_driver_common = Miaou_runner_common__Tui_driver_common
